### ISSUE TITLE
Convert this repo to use Cake.Recipe

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Plist#11]
@reicheltp I am pretty much at the point where my not so secret project, Cake.Recipe, is ready to be rolled out.

Would you be interested in me adding it to this repository?

The benefits would be...

- a single place to control all the builds in the cake-contrib organisation
- access to notifications on twitter and gitter when new releases are available

Things that Cake.Recipe already does:

- Version with GitVersion
- Build
- Compile
- Run Unit Tests
- Submit results to coveralls.io
- NuGet Package everything
- Upload all artifacts to AppVeyor
- Runs DupFinder
- Runs InspectCode
- Handles publishing to both MyGet and NuGet (for interim releases)
- Runs GitLink, meaning that addin code is debuggable doing debug session in visual studio when debugging build.cake
- Documentation Website generation using Wyam

Probably other stuff that I have forgotten.

The main thing being, if we add something to Cake.Recipe, then all projects that are already using Cake.Recipe should be able to immediately take advantage of it.

Thoughts?  If you were interested, would you be happy to have me make the changes directly to repo, or would you prefer it as a PR?

**Comment by reicheltp** [comment]
Hi @gep13 
Actually I've taken a look at Cake.Recipe some days ago and it looks pretty nice. I shortly tried to convert my adding by my self but surrendered some minutes later and postponed it. 😆 

Feel free to make the changes; a PR is not necessary. If you add it for one of my addin or provide me some docs I can support you as well.

**Comment by gep13** [comment]
@reicheltp perfect.  Yes, there is a little bit of a learning curve, and some documentation is required.  I am basically in the stage of running it on other repos that I haven't been in control of, in order to iron out any wrinkles, and from there, I was going to complete the docs.

Will let you know if I run into anything when I get to this repo.  Thanks!

**Comment by gep13** [comment]
@reicheltp ok, so this work is essentially complete.  Would love it if you could take a look and let me know if you have any feedback.  I still need to provide documentation for Cake.Recipe in general, but still in a phase of working out the kinks, before fully publishing it.

There is an issue with the Travis build currently, which I will work on, and hopefully get working soon.
