### ISSUE TITLE
Can't use dynamic in my build-script

### ISSUE THREAD

**Issue by anrichter** [cake-contrib/Cake.Plist#14]
Hi,

as mentioned in the Readme i have to use dynamic as the type for DeserializePlist. That works perfectly on a Mac. But does not compile on a Windows machine.

    error CS8000: This language feature ('dynamic') is not yet implemented in Roslyn.

I can reference CSharp.dll to fix the problem on Windows machines. 

    #reference "Microsoft.CSharp.dll"

But this does not work anymore on macOS. 

    Error: Could not load file or assembly 'Microsoft.CSharp.dll' or one of its dependencies

What a dilemma ;)

My background:
I have a Xamarin App for iOS, Android and UWP. My build.cake script contains build-definitions for all three plattforms and runs on two different machines (macOS & Windows).

Do you have any suggestion? Any fix?
Or is it possible to change the result from DeserialzePlist from dynamic to a strongly typed object, like [Android.AppManifest](https://github.com/ghuntley/Cake.AndroidAppManifest) does it?

Thanks for help & Greetings,
Andreas

**Comment by gep13** [comment]
@anrichter on your windows build, pass in the `-Experimental` flag to the bootstrapper file. Hopefully that will help.

**Comment by anrichter** [comment]
Thanks for the hint, @gep13 
Unfortunateley i get this error

    Error: (2,1): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'

**Comment by gep13** [comment]
@anrichter can you share the script that you are trying to run?

**Comment by anrichter** [comment]
Here is a stripped down version of the script:

```
// Tools
#tool "nuget:?package=GitVersion.CommandLine"

// Addins
#addin "Cake.AndroidAppManifest"
#addin "Cake.FileHelpers"
#addin "Cake.Plist"

// Arguments
var target = Argument("target", "Default");

// Variables
var buildDir = MakeAbsolute(Directory("./build"));
var gitVersion = GitVersion(new GitVersionSettings{ OutputType = GitVersionOutput.Json });

// Tasks
Task("Default")
    .Does(() => {
    });

Task("Clean")
    .Does(() => {
        CleanDirectory(buildDir);
    });

Task("Version")
    .IsDependentOn("Clean")
    .Does(() => {
        GitVersion(new GitVersionSettings { UpdateAssemblyInfo = true });
    });

// Android-Tasks
Task("Android-Version")
    .IsDependentOn("Version")
    .Does(() => {
        var appManifestFile = "./Android/Properties/AndroidManifest.xml";
        var appManifest = DeserializeAppManifest(appManifestFile);
        
        int preReleaseNumber = 0;
        int.TryParse(gitVersion.PreReleaseNumber, out preReleaseNumber);
        
        appManifest.VersionName = gitVersion.MajorMinorPatch + "." + gitVersion.PreReleaseNumber;
        appManifest.VersionCode = gitVersion.Major * 10000000 +
                                  gitVersion.Minor *   100000 +
                                  gitVersion.Patch *     1000 +
                                  preReleaseNumber;

        SerializeAppManifest(appManifestFile, appManifest);
    });

// iOS
Task("iOS-Version")
    .IsDependentOn("Version")
    .Does(() => {
        var plist = File("./src/iOS/Info.plist");
        dynamic data = DeserializePlist(plist);

        data["CFBundleShortVersionString"] = gitVersion.MajorMinorPatch;
        data["CFBundleVersion"] = gitVersion.MajorMinorPatch + "." + gitVersion.PreReleaseNumber;

        SerializePlist(plist, data);
    });

// UWP-Tasks
Task("UWP-Version")
    .IsDependentOn("Version")
    .Does(() => {
        ReplaceRegexInFiles(
            "./src/UWP/Package.appxmanifest", 
            "\\sVersion=\".*\"", 
            string.Format(" Version=\"{0}\"", gitVersion.MajorMinorPatch + "." + gitVersion.PreReleaseNumber));
    });

// Run Task
RunTarget(target);
```

**Comment by tstewart65** [comment]
You need to have a reference to Microsoft.CSharp.dll in the script and use the -experimental switch so it uses a newer version of Roslyn.

#reference "Microsoft.CSharp.dll"

**Comment by anrichter** [comment]
I found a solution for the problem:

I pass -Mono on the windows build. So Cake will run in the Mono scripting engine who knows the dynamic keyword.

Thanks for your help & Cheers,
Andreas
