### ISSUE TITLE
Update to Cake.Core version 0.22

### ISSUE THREAD

**Issue by toddstewart** [cake-contrib/Cake.Plist#17]
Cake.Plist needs to be updated to use Cake.Core version 0.22 so that it can be used with Cake version 0.22.

**Comment by domyd** [comment]
I submitted a PR #18. Can anyone take a look at it? ( @gep13 )

**Comment by aloisdeniel** [comment]
Yep need this merge too, because at the moment we can't use it with `Cake.MobileCenter` which is frustrating!

**Comment by gep13** [comment]
@toddstewart @domyd @aloisdeniel this should now be available in the latest version of Cake.Plist.
