### ISSUE TITLE
Plist parse failure on OSX

### ISSUE THREAD

**Issue by ghuntley** [cake-contrib/Cake.Plist#3]
```
#addin "Cake.Plist"

Task("defect").Does(() =>
{
    var plist = File("./Info.plist");

    // Executing task: defect
    // An error occured when executing task 'defect'.
    // Error: Data at the root level is invalid. Line 1, position 1.
    var data = DeserializePlist(plist);

    //data["CFBundleShortVersionString"] = "1.1.1";
    //data["CFBundleVersion"] = "1.1.1+3131";

    //SerializePlist(plist, data);
});

// EXECUTION
RunTarget("defect");
```

Clone https://github.com/ghuntley/repros/tree/master/cake.plist for a working repro

**Comment by donnib** [comment]
I am experiencing exact same issue. It would be nice to know a workround.

**Comment by reicheltp** [comment]
Hi @donnib I'll fix this issues this weekend. :)

**Comment by ghuntley** [comment]
Excellent :+1:

**Comment by donnib** [comment]
@reicheltp Hey Paul, any progress on this ? ;)

**Comment by reicheltp** [comment]
@donnib Yeah I have tested around a lot but I couldn't find the mistake. Maybe something with the BOM from UTF8 but not sure. The plist I've copied into the test project are mysteriously working. 😞 
As a workaround try to save your plist again with text editor.

Nevertheless, I will do my best to find some time this week to finally fix this stuff.

**Comment by donnib** [comment]
Yes i did also my own trials and it's kind of weird, i did try to look at the BOM and UTF8 but could not see anything wrong but nevertheless Cake.plist still failed.....hmmm

**Comment by donnib** [comment]
I am not sure that i get exact same problem as @ghuntley but i get following 

`Error: Data at the root level is invalid. Line 1, position 1.`

What's weird is that i get this not matter what path i put in `var plist = File("blabla")` or even if i put some garbage stuff in. I would have expected an exception that the path was invalid or that it couldn't find the file.

**Comment by reicheltp** [comment]
I found the bug and it was so obviously that I didn't see it. Since `FilePath` can be casted into `string`, the Roslyn compiler picked the wrong extension method: `PlistAliases.DeserializePlist(this ICakeContext context, string xml)` instead of `PlistAliases.DeserializePlist(this ICakeContext context, FilePath file)`. And that we can't deserialize a file path as xml is evident. 😆 

I renamed the deserialize XML alias and deploy a new NuGet Package later today.

**Comment by donnib** [comment]
great, that explains everything, thx

**Comment by reicheltp** [comment]
Package is deployed and soon available on NuGet. https://www.nuget.org/packages/Cake.Plist/0.2.0

**Comment by ghuntley** [comment]
Confirmed that v0.2.0 works on OSX. Excellent 👍  thanks @reicheltp
