### ISSUE TITLE
Change signature from SerializePlist(dynamic object, File file) to SerializePlist(File file, dynamic object);

### ISSUE THREAD

**Issue by ghuntley** [cake-contrib/Cake.Plist#5]
The order for the method `SerializePlist` is inverted from usual .NET conventions. This would be a breaking change but considering we are still in pre 1.x days and there are less than 3 known users now is a good time to make amends.

MSDN:

```
        System.IO.File.WriteAllText(@"C:\Users\Public\TestFolder\WriteText.txt", text);
```

Thoughts?

**Comment by reicheltp** [comment]
The signature already is the one you suggest:

``` csharp
public static void SerializePlist(this ICakeContext context, FilePath file, object value)
```

See: https://github.com/reicheltp/Cake.Plist/blob/develop/src/Cake.Plist/PlistAliases.cs#L77

Or do I misunderstood something?

**Comment by ghuntley** [comment]
My bad, apologies @reicheltp - on another topic - The Android equivalent is now available. https://github.com/ghuntley/Cake.AndroidAppManifest/
